# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: false
  branches:
   include:
    - master
  paths:
   exclude:
     - contracts/*

steps:
# - task: UseDotNet@2
#   displayName: 'Install net core SDK'
#   inputs:
#     packageType: 'sdk'
#     version: '5.0'
#     includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: 'WebPage//MVCPage/MVCPage.csproj'

  
