# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: false
  branches:
   include:
    - master
  paths:
   exclude:
     - contracts/*
pool:
   vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:

- job: Push
  steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'



  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj;!**/*.Tests.csproj'
      packDirectory: '$(System.DefaultWorkingDirectory)'
      versioningScheme: 'off'
  - task: NuGetCommand@2
    displayName: 'nuget push'
    inputs:
      command: 'push'
      feedsToUse: 'select'
      packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;!$(System.DefaultWorkingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'TestFeed'
      versioningScheme: 'off'
      allowPackageConflicts: true
  - task: NuGetCommand@2
    displayName: 'nuget push'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: '40ad2fc0-aab6-4429-9ed3-153813e66de6/3eea94e8-de7d-4d79-83fc-9f5629a8d2f8'
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'off'
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      
   